# Generated by Django 5.0.6 on 2024-07-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.bookingstatus'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
