# Generated by Django 5.0.6 on 2024-06-20 20:12

from django.db import migrations, models

def add_collection(apps, schema_editor):
    Collection = apps.get_model('Collections', 'Collection')
    collections = [
        'Broadcasting Equipment',
        'Networking Equipment',
        'Studio and Production Equipment',
        'Vehicles',
        'Office Equipment'
    ]
    for collection_name in collections:
        Collection.objects.create(name=collection_name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(add_collection), # This line will execute the add_collection function
    ]
