# Generated by Django 5.0.6 on 2024-06-20 20:12

from django.db import migrations, models

def add_location(apps, schema_editor):
    Location = apps.get_model('Locations', 'Location')
    locations = [
        ('GBC Volta Star Radio', 'Ho'),
        ('GBC Radio Central', 'Cape Coast'),
        ('GBC Twin City Radio', 'Sekondi-Takoradi'),
        ('GBC Radio Savannah', 'Tamale'),
        ('GBC Garden City Radio', 'Kumasi'),
        ('GBC URA Radio', 'Bolgatanga'),
        ('GBC Radio BAR', 'Sunyani'),
        ('GBC Northern Star Radio', 'Wa'),
        ('GBC Obonu FM', 'Tema'),    ]
    for name, city in locations:
        Location.objects.create(name=name, city=city)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(add_location), # This line will execute the add_collection function
    ]
