# Generated by Django 5.0.6 on 2024-06-19 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='0000000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.collection'),
        ),
    ]
