# Generated by Django 5.0.6 on 2024-06-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Items.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Items.collection'),
        ),
    ]
