# Generated by Django 5.0.6 on 2024-06-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_remove_item_available_item_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='0000000000', max_length=50),
        ),
    ]
