# Generated by Django 5.0.6 on 2024-06-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0001_initial'),
        ('Items', '0004_alter_item_collection_alter_item_location_and_more'),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Collections.collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Locations.location'),
        ),
    ]
