# Generated by Django 5.0.6 on 2024-07-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0001_initial'),
        ('Items', '0005_item_available_alter_item_collection_and_more'),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Collections.collection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.location'),
        ),
    ]
